# Generated by Django 5.1.3 on 2024-11-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovsmanager',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
