# Generated by Django 5.1.3 on 2024-11-09 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVSMirror',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('dst_ports', models.ManyToManyField(related_name='dst_ports_mirror', to='port.ovsport')),
                ('out_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.ovsport')),
                ('src_ports', models.ManyToManyField(related_name='src_ports_mirror', to='port.ovsport')),
            ],
        ),
    ]
