# Generated by Django 5.1.3 on 2024-11-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OVSBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovs_name', models.CharField(max_length=20)),
                ('friendly_name', models.CharField(max_length=20)),
                ('description', models.TextField(default=None, null=True)),
            ],
        ),
    ]
