# Generated by Django 5.1.3 on 2024-11-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mirror', '0001_initial'),
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovsmirror',
            name='dst_ports',
            field=models.ManyToManyField(related_name='dst_ports_mirror', to='port.ovsport'),
        ),
        migrations.AddField(
            model_name='ovsmirror',
            name='out_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.ovsport'),
        ),
        migrations.AddField(
            model_name='ovsmirror',
            name='src_ports',
            field=models.ManyToManyField(related_name='src_ports_mirror', to='port.ovsport'),
        ),
    ]
