# Generated by Django 5.1.3 on 2024-11-09 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVSPort',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.ovsbridge')),
            ],
        ),
    ]
